#! /usr/bin/env python

import sys
import os

from geotools import (fetch_data,
                      URI,
                      STATES,
                      )

if __name__ == "__main__":
    from optparse import OptionParser as P
    p = P(description="Fetches geolocation data by state from api.sba.gov.",
          version='0.1-alpha',
          prog=os.path.basename(__file__),
          usage="python %prog [options]",
          epilog="This file can also be used as a module.")
    p.add_option('-v', '--verbose', action='store_true', dest="verbose",
                 help='Will print out the state currently being fetched to stdout.')
    p.add_option('-S', '--state', action='store', dest='state',
                 help='Select a state to fetch geolocation data about using the two capital letter abbreviation, e.g. CA for California.')
    opts, args = p.parse_args()

    if opts.state:
        if opts.verbose: print("Fetching %s..." % opts.state)
        try:
            fetch_data(URI, opts.state, '%s.json' % opts.state)
        except ValueError:
            print("Error: '%s' is not a valid state abbreviation." % opts.state)
            sys.exit(1)
        except OSError:
            print("Error: Check your paths.")
        except Exception, e:
            print("Error: Check your internet connection: %s" % e)
            sys.exit(1)
        sys.exit(0)
    else:
        print('here')
        for state in STATES:
            if opts.verbose: print("Fetching %s..." % state)
            try:
                fetch_data(URI, state, '%s.json' % state, file_uri='data')
            except:
                print("Error: Check your internet connection.")
                sys.exit(1)
        sys.exit(0)
